#!/bin/bash
# Entrypoint script for crawlrs container
# Fix DNS resolution issues by using external DNS servers

echo "[entrypoint] Setting up DNS configuration..."

# Backup original resolv.conf
if [ -f /etc/resolv.conf ]; then
    cp /etc/resolv.conf /etc/resolv.conf.backup
fi

# Write new DNS configuration with external DNS servers
cat > /etc/resolv.conf << 'EOF'
# Generated by crawlrs entrypoint script
# Using external DNS servers for external domain resolution
nameserver 8.8.8.8
nameserver 114.114.114.114
options timeout:2 attempts:3
EOF

echo "[entrypoint] DNS configuration updated:"
cat /etc/resolv.conf

echo "[entrypoint] Starting crawlrs..."

# Execute the main command
exec "$@"
